In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("startup_meta_ads.csv")

In [3]:
dataset

     Meta Ads Spend  Administration  Marketing Spend       State  Profit
0            141958           38110           193734  California  179760
1            166867          109309           108506  California  184200
2            151932           57266           119751  California  169790
3            123694           82992           297486    New York  206505
4            139879          112948           178229  Washington  149284
..              ...             ...              ...         ...     ...
115          143684          134095            66958       Texas  150943
116           30965           56309            92074  California   56197
117           44538          117455            20729  California   41719
118          128066           93734           240785  Washington  189266
119          133252          100467           186089    New York  149016

[120 rows x 5 columns]

In [4]:
independent=dataset[["Meta Ads Spend","Administration","Marketing Spend"]]

In [5]:
independent

     Meta Ads Spend  Administration  Marketing Spend
0            141958           38110           193734
1            166867          109309           108506
2            151932           57266           119751
3            123694           82992           297486
4            139879          112948           178229
..              ...             ...              ...
115          143684          134095            66958
116           30965           56309            92074
117           44538          117455            20729
118          128066           93734           240785
119          133252          100467           186089

[120 rows x 3 columns]

In [7]:
dependent=dataset["Profit"]

In [8]:
dependent

0      179760
1      184200
2      169790
3      206505
4      149284
        ...
115    150943
116     56197
117     41719
118    189266
119    149016
Name: Profit, Length: 120, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    independent,
    dependent,
    test_size=0.30,
    random_state=0
)

In [10]:
x_train

     Meta Ads Spend  Administration  Marketing Spend
6             74886           36910            99045
75            75591          128098           181890
100           32666          145386           151564
91           153767          113211           134123
104           84505          142859           226386
..              ...             ...              ...
67           196830          135830           295472
64            72995          122787           104179
117           44538          117455            20729
47           161699          142235           284327
44            23890           32693            76690

[84 rows x 3 columns]

In [11]:
x_test

     Meta Ads Spend  Administration  Marketing Spend
48            28792           99163           153946
94           156330          139953           173707
95            59504          119474           275564
8            188266          120982           120078
97            33986           97172           125294
22           105305           48141            81295
7            157337          140989            44698
10           132727           30206            96202
45            61606          125003            14499
89            22568           69353           115983
33           149981          111734           117512
50           174969           78925           277683
2            151932           57266           119751
60           100077           60080            87505
119          133252          100467           186089
74            21016          127504           117450
30            22747           63827            40306
43            89092          139556            25151
111          109135           76717            82991
76            43247           43545           291974
63            98953           36776           122296
59           126530           53776           129121
16            84820           80015           236814
24           150608          135878           283255
110           72256           85680           252289
13            36023           53419           143883
54           174555           56105           223090
93           199262           95318           188274
26           104478           86044            18155
68            57065           88053           145059
51            88148           72941           194423
113           55222          117092           283237
107           28392          120084           175656
61            55920           96842            12869
3            123694           82992           297486
96           184231           53664           141373

In [12]:
y_train

6       93729
75     122231
100     90683
91     180864
104    133443
        ...
67     234440
64      86750
117     41719
47     227136
44      57030
Name: Profit, Length: 84, dtype: int64

In [13]:
y_test

48      85425
94     174513
95     145579
8      187127
97      56293
22      99893
7      140043
10     118415
45      56824
89      57243
33     168734
50     208924
2      169790
60     110779
119    149016
74      33214
30      21627
43      63922
111    118461
76     103251
63     131121
59     127360
16     146372
24     205820
110    131240
13      79105
54     187299
93     219516
26      86237
68      90533
51     111759
113    110472
107     83705
61      65535
3      206505
96     176852
Name: Profit, dtype: int64

In [14]:
from sklearn.ensemble import GradientBoostingRegressor

regressor = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1)

In [15]:
regressor

GradientBoostingRegressor()

In [17]:
regressor = GradientBoostingRegressor()
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)
print(y_pred)

[ 75881.58367066 186561.99148004 128706.45210738 189761.210133
  71894.28478015 102696.10703682 168818.36145897 145944.59035374
  68806.97717685  75131.12431841 149964.80674571 208167.0586773
 159098.64186868 101475.41101316 161994.12935794  71539.91187565
  37432.39259529  97301.87638512 111261.1944825  109479.527302
 113566.1905749  147383.40001234 138885.75368305 202456.36590094
 133939.33576754  76689.36613113 196154.93474715 185629.91571445
  80643.24488689  86576.1906924  141483.32530097 114961.34333738
  77782.49614553  59236.85578224 178313.78435595 192276.26048744]

In [18]:
from sklearn.metrics import r2_score
r2_score

In [19]:
r_score=r2_score(y_test,y_pred)
r_score

0.8920947093043192

In [20]:
import pickle
filename="Gradientboost_final.sav"

In [21]:
pickle.dump(regressor,open(filename,"wb"))

In [22]:
loaded_model=pickle.load(open("Gradientboost_final.sav",'rb'))
result=loaded_model.predict([[55413,14567,365448]]) 
result

C:\Users\premchandar\Anaconda3\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  "X does not have valid feature names, but"

array([128950.67409559])